"""Ranges, steps, and help text for Streamlit controls."""

from __future__ import annotations

CONTROL_RANGES = {
    "A_s": {"min": 0.5e-9, "max": 3.5e-9, "default": 2.1e-9, "step": 0.05e-9, "format": "%.2e"},
    "n_s": {"min": 0.90, "max": 1.05, "default": 0.965, "step": 0.001, "format": "%.3f"},
    "k_pivot": {"min": 0.002, "max": 0.1, "default": 0.05, "step": 0.001, "format": "%.3f"},
    "H0": {"min": 55.0, "max": 80.0, "default": 67.81, "step": 0.01, "format": "%.2f"},
    "Omega_m": {"min": 0.20, "max": 0.45, "default": 0.3098830430481205, "step": 0.0001098830430481205, "format": "%.6f"},
    "Omega_b": {"min": 0.035, "max": 0.065, "default": 0.0493, "step": 0.0001, "format": "%.4f"},
    "Omega_k": {"min": -0.05, "max": 0.05, "default": 0.0, "step": 0.001, "format": "%.3f"},
    "N_eff": {"min": 2.0, "max": 4.5, "default": 3.046, "step": 0.001, "format": "%.3f"},
    "Tcmb": {"min": 2.70, "max": 2.75, "default": 2.7255, "step": 0.0001, "format": "%.4f"},
    "tau_reio": {"min": 0.03, "max": 0.09, "default": 0.06, "step": 0.001, "format": "%.3f"},
    "f_EDE": {"min": 0.00, "max": 0.20, "default": 0.10, "step": 0.005, "format": "%.3f"},
    "log10_a_c": {"min": -4.5, "max": -2.5, "default": -3.5, "step": 0.01, "format": "%.2f"},
    "k_min": {"min": 1e-5, "max": 1e-3, "default": 1e-4, "step": 1e-5, "format": "%.5f"},
    "k_max": {"min": 10.0, "max": 300.0, "default": 200.0, "step": 1.0, "format": "%.0f"},
    "k_points": {"min": 300, "max": 3000, "default": 1200, "step": 50},
    "quad_limit": {"min": 100, "max": 500, "default": 200, "step": 10},
    "delta_c": {"min": 1.5, "max": 1.9, "default": 1.686, "step": 0.001, "format": "%.3f"},
    "mass_min_exp": {"min": 8, "max": 12, "default": 8, "step": 1},
    "mass_max_exp": {"min": 12, "max": 16, "default": 15, "step": 1},
    "mass_points": {"min": 40, "max": 250, "default": 80, "step": 5},
    "selected_mass_exp": {"min": 8, "max": 15, "default": 12, "step": 1},
    "single_z": {"min": 0.0, "max": 100.0, "default": 0.0, "step": 0.1, "format": "%.1f"},
}

CONTROL_HELP = {
    "mode": "Learning mode keeps explanations prominent. Research mode keeps the same physics controls available for comparison workflows.",
    "A_s": "Primordial scalar amplitude. Raising it lifts the initial fluctuation amplitude and usually raises sigma(M).",
    "n_s": "Scalar spectral tilt. It shifts relative power between large-scale and small-scale modes.",
    "k_pivot": "Reference wavenumber for the primordial power law, in Mpc^-1.",
    "H0": "Hubble constant today. This sets h = H0 / 100 and affects derived densities.",
    "Omega_m": "Total matter density fraction today.",
    "Omega_b": "Baryon density fraction. Omega_cdm is computed as Omega_m - Omega_b.",
    "Omega_k": "Curvature density fraction. Used in the derived dark-energy closure check.",
    "N_eff": "Effective number of relativistic neutrino species, used in Omega_r.",
    "Tcmb": "CMB temperature today, used in the radiation-density estimate.",
    "tau_reio": "Optical depth to reionization. CLASS uses this when computing the matter power spectrum.",
    "enable_ede": "Turns the Early Dark Energy parameter block on for CLASS settings when available.",
    "f_EDE": "Early Dark Energy fraction near the critical scale factor.",
    "log10_a_c": "Base-10 log of the EDE critical scale factor. The app displays a_c and z_c live.",
    "n_EDE": "Integer EDE potential index.",
    "k_min": "Minimum wavenumber for matter-power sampling.",
    "k_max": "Maximum wavenumber for matter-power sampling. Too low can bias low-mass sigma(M).",
    "k_points": "Number of k samples used for P(k). More points can improve resolution but slow CLASS.",
    "quad_limit": "Integration subdivision limit for sigma(M) and growth-related quadrature.",
    "window_type": "Smoothing kernel used when sigma(M) integrates P(k) through W(kR).",
    "fitting": "Halo multiplicity relation used to convert sigma(M,z) into dn/dlnM.",
    "delta_c": "Linear collapse threshold used in peak height and HMF fitting functions.",
    "mass_min_exp": "Minimum log10 halo mass in h^-1 solar masses.",
    "mass_max_exp": "Maximum log10 halo mass in h^-1 solar masses.",
    "mass_points": "Number of halo-mass samples.",
    "selected_mass_exp": "Reference mass exponent for integrand, sensitivity, and teaching diagnostics.",
    "single_z": "Single redshift for redshift-dependent sigma(M,z) and HMF plots.",
    "z_values": "Preset redshifts for multi-redshift comparison plots.",
    "custom_z_list": "Comma-separated extra redshifts to include with the preset selections.",
}
